---
server:  port: 8888spring:  cloud:    config:      server:
        encrypt:          enabled: false        git:          uri: https://github.com/njsurat/spring-cloudconfig-wa-tolls
          #username: uname
          #password: pass
          search-paths:            - 'station*'
          repos:            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/njsurat/spring-cloudconfig-wa-tolls-perf
              search-paths:
                - 'station*'  security:    user:      name: admin
      password: admin